### ISSUE TITLE
Occasional crash on closing the app

### ISSUE THREAD

**Issue by Thurinum** [Thurinum/simple-media-encoder#14]
Doesn't affect functionality, but the program sometimes terminates with a segfault when it's closed. I guess some double deletion or logic error in the serialization is happening.

**Comment by theodore-lheureux** [comment]
![image](https://github.com/user-attachments/assets/208c4cef-4463-403a-ac88-172b11acd527)

**Comment by Thurinum** [comment]
too accurate

**Comment by Thurinum** [comment]
The crash occurs when closing the app **only after the value of a codec dropdown has been changed by clicking on it (not by scrolling with mouse wheel)**.

**Comment by Thurinum** [comment]
Whenever a combobox was clicked on to reveal its contents, the app will segfault upon closing.
Happens even with comboboxes that have designer-set content and no code associated with them.
Also happens when serialization on app close is disabled.

No idea how it happens and it doesn't affect functionality (since it's on app close), so I'll ignore it for now.
