### ISSUE TITLE
Fails to compile (make).

### ISSUE THREAD

**Issue by Impeta** [Thurinum/simple-media-encoder#2]
The instructions to compile it are very straightforward and simple! Still, I can't seems to do it somehow. Must be missing some more dependencies or so. [Here's the log.](https://paste.tildeverse.org/?bc808d5b1661aac0#wZ318iiokkyLBLSvsbTES6Qk4mnsE9rX1pwdtTETjWU)

For reference, yes, I've got `qt6-tools`, `ffmpeg` and `make` already, and I did input `qmake SimpleMediaEncoder.pro` before. OS is EndeavourOS, Arch-based distro.

**Comment by Thurinum** [comment]
Many thanks for reporting this issue! I will investigate later today.

**Comment by Thurinum** [comment]
I'm able to reproduce the issue on a Debian-based distro. 
Based on the logs, it looks like the problem is that Qt 5 is being used rather than Qt 6.

Could you try `qmake -v` and report the Qt version shown?

**Comment by Thurinum** [comment]
Using `apt`, I was not able to find a package for Qt 6 without fiddling with sources.list... however, you might have better luck with `pacman` and the AUR!

Looks like the easiest way is to use the [official Qt installer](https://www.qt.io/download-qt-installer). It should work perfectly out of the box, though it requires a free account. I will update the readme later with this in mind...

Thanks again for taking the time to troubleshoot this issue! Let me know what worked best for you.

**Comment by theodore-lheureux** [comment]
You can install [qt6-base ](https://archlinux.org/packages/extra/x86_64/qt6-base/), then use `qmake6` instead of `qmake` and it should work.
