### ISSUE TITLE
Windows binary needs QT6

### ISSUE THREAD

**Issue by tyeeman** [Thurinum/simple-media-encoder#20]
Well that's the error I get. I thought everything needed would be in the binary?

**Comment by Thurinum** [comment]
Yeah, thanks for reporting! The binaries weren't deployed correctly and the Qt dlls were missing.
Should be fixed now in [the latest release](https://github.com/Thurinum/simple-media-encoder/releases/tag/v0.11.1-win64).

**Comment by tyeeman** [comment]
Thanks, works now. Looks like I have one version too old driver for nvenc. 

```Driver does not support the required nvenc API version. Required: 12.2 Found: 12.1```

If I used an older version of ffmpeg would that work?

It would be nice to see the full command line your app is generating before the encode starts. 

One new thing that would be nice is to save your own preset.

Good work! Looks very useful.

**Comment by Thurinum** [comment]
Glad it works!
<br>

> If I used an older version of ffmpeg would that work?

I would update the Nvidia driver first.
<br>
> It would be nice to see the full command line your app is generating before the encode starts.

Good idea, currently it only shows up when something goes wrong, for diagnostics.
<br>
> One new thing that would be nice is to save your own preset.

You can do that by editing presets.ini at the moment. Not very user-friendly, though.

**Comment by tyeeman** [comment]
I did try an older ffmpeg and it does work.

For Presets I meant save my own command lines, not the gui settings. 

I just ran an encode with ``desired file size``` set to Auto Megabytes. So I'm wondering what command line is passed to ffmpeg? Is it using CRF or Bitrate and what values?
