### ISSUE TITLE
Error when starting to run

### ISSUE THREAD

**Issue by tyeeman** [Thurinum/simple-media-encoder#5]
I get this error - 
```
procedure entry point CreateEventW could not be located api-ms-win-core-synch-l1-2-0.dll
```
I'm on win7. This file is on my system. Does this only run on newer versions of Windows?

**Comment by Thurinum** [comment]
Hello! Thanks for taking the time to report this issue.

Unfortunately, the Qt 6 framework used by this tool is not compatible with Windows 7, which is a discontinued version of Windows. Adding support would require backporting to Qt 5, which is not currently planned. 

I will make sure to update the README so the compatibility is clearer. 

Cheers
